feature/name agnostic
ucsc-cgp/bagit-firecloud-lambda pull request #17
Opened 2018-04-27 17:47 UTC by mjkrause

* accepts any bag name, and TSV files can be any name, but must end on '.tsv'
* identifies participant and sample TSV file, and uploads in correct order
 * tests are in `test_TSV_identification.py`
 * found that deleting the bag in `/tmp` of the AWS Lambda is a requirement, otherwise files with different names will accumulate
 * this hadn't been detected previously, perhaps because we always used the same TSV file names, and they were overwritten
 * tested Lambda (using `curl`) with 
     * manifest zip file with 2 TSV files, named
 `participant.tsv` and `sample.tsv`
     * zip file that contains 3 TSV files
     * zip file that contains duplicate entries
     *  zip file that has different bag and TSV file names

2018-04-27 22:15 UTC, coverbeck requested changes

2018-04-27 22:15 UTC, coverbeck commented on app.py
> +    to be ".tsv". It creates a new workspace in a FireCloud namespace,
It doesn't necessarily create a new workspace.

2018-04-27 22:15 UTC, coverbeck commented on app.py
> +    if isinstance(data, Response):
It feels wrong to me to have a method return two totally different types of data; in your case either a Response object or a JSON object.

I would instead throw an Exception from get_data, and catch it. Maybe ask a more experienced Python programmer what they think?

2018-04-27 22:15 UTC, coverbeck commented on app.py
> +    delete_files_from_path(path)
I don't think you should delete the /tmp directory. https://unix.stackexchange.com/questions/11235/is-it-safe-to-rm-rf-tmp

While this *may* be safe on your lambda instance, since perhaps they give a /tmp directory with nothing in it, it seems like it's fragile. Plus, if there's stuff in there, you are unnecessarily wasting time deleting files when you don't need to.

The approach you should take is look at the zip file and see what the root directory is in it, then look for that directory when you extract. 

To be extra safe, you should probably extract to a temporary directory in the unlikely event that the directory name in the zip collides with some existing directory in /tmp.

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +        return Response(body={'message': msg},
You need to return an error status code. Since this case means that the data submitted was incorrect, meaning it is a user correctable error, you should set status code to 400.

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +                    body={'message': 'TSV files have wrong headers'},
Set status code to 400

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +def delete_files_from_path(path):
See other comment; I don't believe you should go down this route.

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +            col_names = f.readline().strip('\n')
You should do a `split(',')` to get the column names as an array.

Otherwise, although it's extremely unlikely, the column name `entity:participant_idblahblah` will match

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +    eventflag = None  # make loop execution dependent on event flag values
IDE is giving me a warning for this... should probably be `event_flag`.

2018-04-27 22:15 UTC, coverbeck commented on tests/test_TSV_identification.py
> +        self.assertListEqual(arr_files,
This fails for me when I run the unit test. The three files are there but in a different order. You can't rely on `os.listdir()` always returning files in the same order.

```
AssertionError: Lists differ: ['participant.tsv', 'sample.tsv', 'sample2.tsv'] != ['participant.tsv', 'sample2.tsv', 'sample.tsv']

First differing element 1:
'sample.tsv'
'sample2.tsv'

- ['participant.tsv', 'sample.tsv', 'sample2.tsv']
+ ['participant.tsv', 'sample2.tsv', 'sample.tsv']
```

2018-04-27 22:15 UTC, coverbeck commented on chalicelib/utils.py
> +    """Delete all files in /tmp."""
If for some reason you keep this function, to delete the extracted zip file after you are finished processing it, then your comment should say you are deleting files in `path`, not `/tmp`.

2018-04-27 22:15 UTC, coverbeck commented on tests/test_TSV_identification.py
> +#!/usr/bin/env python
You now have two test files. And I noticed belatedly that the one test file used to be called test_manifest_io.py.

In Java and JavaScript, the test files' names are based on the file they are testing. That way if you in a source file, you can easily locate the corresponding tests. That sort of seems to be the pattern in Python, although I couldn't find it written down anywhere. I did find a couple of repos that seem to follow the same pattern.

I would have one test file, `test_utils.py`, and then have the two test classes inside.

2018-04-27 23:54 UTC, coverbeck commented on chalicelib/utils.py
> +            col_names = f.readline().strip('\n')
I was just looking at the FC code, to understand how they implement authorization. You need to make sure that entity:particpant_id is the first column, not just any column.

2018-05-02 02:45 UTC, cricketsloan commented
➤ Cricket Sloan commented:

This is collapsed with #BFL‌-3

2018-05-02 02:50 UTC, closed without merging