Feature/add specs to readme
ucsc-cgp/bagit-firecloud-lambda pull request #4
Opened 2018-03-20 23:51 UTC by mjkrause

* added specs to README, incl. flow diagram and new Lambda endpoint
* added try / except constructs to handle HTTP reponses
* redeployed AWS Lambda and tested it using curl
* added two more parameters to `.chalice/config.json`
* updated `requirements.txt`
* `ManifestIO.import_tsv_to_fc` not returns only the status code if all responses were OK, otherwise HTTP error messages are send to stdout

primary reviewer @coverbeck

2018-03-21 18:30 UTC, coverbeck requested changes

2018-03-21 18:30 UTC, coverbeck commented on chalicelib/utils.py
>              return False
You should return the status code and pass that back on to the client.

2018-03-21 18:30 UTC, coverbeck commented on chalicelib/utils.py
> +            sys.exit(1)
You should not do an exit, you should return the status code to the client

2018-03-21 18:30 UTC, coverbeck commented on chalicelib/utils.py
> +            sys.exit(1)
Same as above; you should return status code to client.

2018-03-21 18:30 UTC, coverbeck commented on chalicelib/utils.py
> +
Should return status code

2018-04-05 23:58 UTC, coverbeck commented
Is this PR still active? Seems like some of it was already done, e.g., removal of pandas.

2018-04-06 15:23 UTC, closed without merging

2018-04-06 15:57 UTC, mjkrause commented
I opened a [PR](https://github.com/DataBiosphere/bagit-firecloud-lambda/pull/11) that addresses your point.